version: '3'

services:
  app:
    build: ./app
    restart: always
    networks:
      - app
    volumes:
      - "./conf:/app/conf:ro"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - "./games:/usr/share/nginx/html/games:ro"
    networks:
      - app


networks:
  app:
